/**
 * Created by zhu on 2016/10/20.
 *
 */
const routers=[
    {
        path:'/',
        component(resolve){
            require.ensure(['./components/index.vue'],()=>{//require.ensure依赖加载
                resolve(require('./components/index.vue'))//打包切割
            },"index");//打包后的名称
        }
    },
    {
        path:'/brand',
        component(resolve){
            require.ensure(['./components/brand.vue'],()=>{
                resolve(require('./components/brand.vue'))//打包切割
            },"brand");
        }
    },
    {
        path:"/branDetail",
        component(resolve){
            require.ensure(['./components/brand-detail.vue'],()=>{
                resolve(require('./components/brand-detail.vue'))//打包切割
            },"brand-detail");
        }
    },
    {
        path:"/course",
        component(resolve){
            require.ensure(['./components/course.vue'],()=>{
                resolve(require('./components/course.vue'))//打包切割
            },"course");
        }
    },
    {
        path:"/courseDetail",
        component(resolve){
            require.ensure(['./components/course-detail.vue'],()=>{
                resolve(require('./components/course-detail.vue'))//打包切割
            },"course-detail");
        }
    },
    {
        path:"/activity",
        component(resolve){
            require.ensure(['./components/activity.vue'],()=>{
                resolve(require('./components/activity.vue'))//打包切割
            },"activity");
        }
    },
    {
        path:"/activityList",
        component(resolve){
            require.ensure(['./components/activity-list.vue'],()=>{
                resolve(require('./components/activity-list.vue'))//打包切割
            },"activity-list");
        }
    },
    {
        path:"/activityDetail",
        component(resolve){
            require.ensure(['./components/activity-detail.vue'],()=>{
                resolve(require('./components/activity-detail.vue'))//打包切割
            },"activity-detail");
        }
    },
    {
        path:"/mba",
        component(resolve){
            require.ensure(['./components/mba.vue'],()=>{
                resolve(require('./components/mba.vue'))//打包切割
            },"mba");
        }
    },
    {
        path:"/mbaList",
        component(resolve){
            require.ensure(['./components/mba-list.vue'],()=>{
                resolve(require('./components/mba-list.vue'))//打包切割
            },"mba-list");
        }
    },
    {
        path:"/mbaDetail",
        component(resolve){
            require.ensure(['./components/mba-detail.vue'],()=>{
                resolve(require('./components/mba-detail.vue'))//打包切割
            },"mba-detail");
        }
    },
    {
        path:"/news",
        component(resolve){
            require.ensure(['./components/news.vue'],()=>{
                resolve(require('./components/news.vue'))//打包切割
            },"news");
        }
    },
    {
        path:"/newsList",
        component(resolve){
            require.ensure(['./components/news-list.vue'],()=>{
                resolve(require('./components/news-list.vue'))//打包切割
            },"news-list");
        }
    },
    {
        path:"/newsDetail",
        component(resolve){
            require.ensure(['./components/news-detail.vue'],()=>{
                resolve(require('./components/news-detail.vue'))//打包切割
            },"news-detail");
        }
    },
    {
        path:"/bespeak",
        component(resolve){
            require.ensure(['./components/bespeak.vue'],()=>{
                resolve(require('./components/bespeak.vue'))//打包切割
            },"bespeak");
        }
    }
];
export default routers;
